### ISSUE TITLE
not enough documentation ?

### ISSUE THREAD

**Issue by slootzky** [flavio/scsgate#8]
Hey, 
sorry that it might not be an issue rather a request.
I think there's not enough documentation in the readme file.
I'm trying to install it right now, I have the SCS server IP but that's all I know.
I find it difficult to understand what's `device` is or how should I configure this scs-monitor to run.
I'm running HA on RPI3 and I have the myhomeserver1.
any help would be much appreciated .
Thanks

**Comment by flavio** [comment]
Do you have the official btcino SCS server (something like https://catalogo.bticino.it/BTI-F454-IT), or do you have [this one](https://goo.gl/aKnpDw)?

Before we go into the details, this project works only with the latter one.

**Comment by slootzky** [comment]
oh boy. 
I have the bticino official one. 
Does this means I can't make it work with HA?

**Comment by gST84** [comment]
You can use this integration with the myhomeserver1.
https://community.home-assistant.io/t/legrand-bticino-myhome/229337

**Comment by slootzky** [comment]
thank you my friend.
